# Generated by Django 5.0.1 on 2024-01-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_courts'),
    ]

    operations = [
        migrations.AddField(
            model_name='courts',
            name='image',
            field=models.ImageField(blank=True, upload_to='./images'),
        ),
    ]
