# Generated by Django 5.0.1 on 2024-01-12 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_courts_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='image',
            field=models.ImageField(blank=True, upload_to='./regions'),
        ),
    ]
