# Generated by Django 5.0.1 on 2024-01-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_region_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='courts',
            name='lat',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='courts',
            name='lng',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='courts',
            name='place_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
