# Generated by Django 5.0.1 on 2024-01-13 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_rename_user_account_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='homepage_picture',
            field=models.ImageField(blank=True, default='./profile_picture/default_homepage.jpg', upload_to='./profile_picture'),
        ),
    ]
