# Generated by Django 5.0.1 on 2024-01-17 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_account_homepage_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='friends',
            field=models.ManyToManyField(blank=True, to='app1.account'),
        ),
    ]
