# Generated by Django 5.0.1 on 2024-01-18 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_account_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='played_matches',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='wins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
