# Generated by Django 5.0.1 on 2024-01-20 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='Creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_match', to='app1.account'),
        ),
        migrations.AlterField(
            model_name='match',
            name='Looser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='losed_matches', to='app1.account'),
        ),
        migrations.AlterField(
            model_name='match',
            name='Winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='app1.account'),
        ),
    ]
