# Generated by Django 5.0.1 on 2024-01-20 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_match_creator_alter_match_looser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='court',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='court_match', to='app1.courts'),
        ),
    ]
