# Generated by Django 5.0.1 on 2024-01-20 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_match_court'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='court_match', to='app1.courts'),
        ),
    ]
