# Generated by Django 5.0.1 on 2024-01-20 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_alter_match_court'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='Creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_match', to='app1.account'),
        ),
        migrations.RemoveField(
            model_name='match',
            name='Joined',
        ),
        migrations.AddField(
            model_name='match',
            name='Joined',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oponent_match', to='app1.account'),
        ),
    ]
