# Generated by Django 5.0.1 on 2024-01-23 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_match_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='refreshed',
            field=models.BooleanField(default=False),
        ),
    ]
