# Generated by Django 5.0.1 on 2024-01-23 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_match_refreshed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='refreshed',
        ),
    ]
