# Generated by Django 5.0.1 on 2024-02-01 23:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_activity',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='friend_notification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app1.notification')),
                ('friend_to_add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_request', to='app1.account')),
            ],
            bases=('app1.notification',),
        ),
    ]
