# Generated by Django 5.0.1 on 2024-02-02 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_account_last_activity_friend_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='party',
            field=models.ManyToManyField(blank=True, to='app1.account'),
        ),
    ]
