# Generated by Django 5.0.1 on 2024-02-03 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_account_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='ranked',
            field=models.BooleanField(default=False),
        ),
    ]
