# Generated by Django 5.0.1 on 2024-02-03 18:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_alter_friend_notification_friend_to_add'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend_requests',
            old_name='data',
            new_name='date',
        ),
        migrations.CreateModel(
            name='party_invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_party', to='app1.account')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_party', to='app1.account')),
            ],
        ),
        migrations.DeleteModel(
            name='friend_notification',
        ),
        migrations.DeleteModel(
            name='notification',
        ),
    ]
