# Generated by Django 5.0.1 on 2024-02-03 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_party_account_party_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='party',
        ),
    ]
