# Generated by Django 5.0.1 on 2024-02-03 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0035_remove_account_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='party_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.party'),
        ),
    ]
