# Generated by Django 5.0.1 on 2024-02-24 19:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0039_result_type_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='date_created',
        ),
        migrations.AddField(
            model_name='match',
            name='date_started',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
