# Generated by Django 5.0.1 on 2024-02-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0041_alter_match_date_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
